# Generated by Django 5.1b1 on 2024-07-23 09:00

import django.db.models.deletion
import django_bleach.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_bleach.models.BleachField(max_length=50, unique=True)),
                ('description', django_bleach.models.BleachField(max_length=250)),
                ('website', django_bleach.models.BleachField(max_length=500)),
                ('phone', django_bleach.models.BleachField(max_length=50)),
                ('email', django_bleach.models.BleachField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('average_rating', models.FloatField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_reviews', to='bootcamp_table.bootcamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
